### ISSUE TITLE
FatalErrorException after installation of this module (version 1.2).

### ISSUE THREAD

**Issue by jszybisz** [pay-now/paynow-prestashop#34]
There is a FatalErrorException after installation of this module (version 1.2). I had previously version 1.1.8 which was uninstalled. 

Please help
![image](https://user-images.githubusercontent.com/7015272/86488107-3dd37600-bd60-11ea-99c3-9ab95e997e83.png)

**Comment by michalskladanowski** [comment]
Od pluginu w wersji v1.2.0 do poprawnego działania wymagane jest PHP w wersji conajmniej 7.1.
Aby przywrócić stronę do działania należy usunąć serwera folderu 'module/paynow'.
__

Since version v1.2.0 of the plugin, PHP 7.1 or higher is required.
To restore the page, please delete the folder 'module/paynow' form the server.

**Comment by jszybisz** [comment]
Tak. Faktycznie zmiana wersji PHP na 7.1 pomogła
Pozdrawiam

pt., 3 lip 2020 o 20:04 michalskladanowski <notifications@github.com>
napisał(a):
